#!/usr/bin/env python3
"""Download the Google Fonts used by the site and self-host them.

Papyr's pitch is that nothing about you leaves your control. Loading fonts from
fonts.gstatic.com would make a third-party request on every page view, which
contradicts that. This script pulls the woff2 files into assets/fonts/webfonts/
and writes assets/fonts.css pointing at the local copies, so the site makes zero
third-party requests.

Only the `latin` and `latin-ext` subsets are kept. Browsers pick per-subset via
unicode-range, so latin-ext costs nothing unless a page actually uses it.

Usage:  python3 scripts/fetch-fonts.py
"""
import os
import re
import urllib.request

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,500"
    "&family=Alegreya+Sans:ital,wght@0,400;0,500;0,700;1,400"
    "&family=IBM+Plex+Mono:wght@500;600"
    "&display=swap"
)
KEEP_SUBSETS = ("latin", "latin-ext")
# A modern UA is required or Google serves legacy ttf instead of woff2.
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"


def opener():
    proxy = os.environ.get("HTTPS_PROXY")
    handler = urllib.request.ProxyHandler({"https": proxy, "http": proxy}) if proxy else urllib.request.BaseHandler()
    op = urllib.request.build_opener(handler)
    op.addheaders = [("User-Agent", UA)]
    return op


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    outdir = os.path.join(root, "assets", "fonts", "webfonts")
    os.makedirs(outdir, exist_ok=True)
    op = opener()

    css = op.open(GOOGLE_CSS, timeout=60).read().decode()
    blocks = re.findall(r"/\*\s*([\w\[\]-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)

    rendered, downloaded = [], {}
    for subset, blk in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", blk).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", blk).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", blk).group(1).strip()
        url = re.search(r"url\((https://[^)]+)\)", blk).group(1)

        # Variable fonts serve one file across several @font-face weights, so key
        # the filename off the URL. Naming per-weight instead would point later
        # blocks at files that were deduped away and never written.
        if url in downloaded:
            slug = downloaded[url][0]
        else:
            slug = f"{family.replace(' ', '')}-{style}-{weight.replace(' ', '_')}-{subset}.woff2"
            data = op.open(url, timeout=60).read()
            with open(os.path.join(outdir, slug), "wb") as fh:
                fh.write(data)
            downloaded[url] = (slug, len(data))
        rendered.append(
            f"/* {family} {style} {weight} — {subset} */\n"
            + re.sub(r"url\(https://[^)]+\)", f"url('fonts/webfonts/{slug}')", blk)
        )

    header = (
        "/* Self-hosted webfonts (latin, latin-ext).\n"
        "   Generated by scripts/fetch-fonts.py — do not edit by hand.\n"
        "   Self-hosted so the site makes no third-party requests, matching Papyr's privacy promise. */\n\n"
    )
    with open(os.path.join(root, "assets", "fonts.css"), "w") as fh:
        fh.write(header + "\n\n".join(rendered) + "\n")

    total = sum(size for _, size in downloaded.values())
    print(f"{len(downloaded)} files, {total // 1024} KB -> assets/fonts/webfonts/")


if __name__ == "__main__":
    main()
